version: "3.9"
services:
  www:
    build: .
    image: www.codl.fr
    restart: unless-stopped
    ports:
      - "9311:80"
    env:
      REDIS_HOST: "redis"

  redis:
    image: redis
    restart: unless-stopped
