version: "3.9"
services:
  www:
    build: .
    image: www.codl.fr
    restart: unless-stopped
    ports:
      - "9311:80"
    env_file: .env
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"

  redis:
    image: redis:6.2
    restart: unless-stopped
