name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        cache: "pipenv"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv sync -d
    - name: Launch redis
      run: docker run -p 6379:6379 -d redis:6.2
    - name: Test with pytest
      env:
        DONPHAN_ACCESS_TOKEN: ${{ secrets.DONPHAN_ACCESS_TOKEN }}
      run: |
        pipenv run pytest
